---
- name: Install Irida and Galaxy on the same host
  set_fact:
    type_of_node: 'all'
  when: irida_server_ip == galaxy_wn_ip

- include_tasks: galaxy_docker.yml
  when: type_of_node == 'galaxy' or
        type_of_node == 'all'

- include_tasks: modify_galaxy.yml
  when: type_of_node == 'galaxy' or
        type_of_node == 'all'

- include_tasks: deploy_irida.yml
  when: type_of_node == 'irida' or
        type_of_node == 'all'
