---

- include_tasks: volume_setup.yml
  when: "'irida' in group_names"

- include_tasks: nfs_server.yml
  when: "'irida' in group_names and ansible_play_batch | unique | length > 1"

- include_tasks: nfs_client.yml
  when: "'galaxy' in group_names and ansible_play_batch | unique | length > 1"

- include_tasks: galaxy_docker.yml
  when: "'galaxy' in group_names"

- include_tasks: deploy_irida.yml
  when: "'irida' in group_names"

- include_tasks: modify_galaxy.yml
  when: "'galaxy' in group_names"

- name: Edit irida.conf file
  template:
    dest: "{{ irida_conf_dir }}/irida.conf"
    src: irida.conf.j2
  notify: Restart tomcat8
  when: "'irida' in group_names"