---

- name: Download user creation script   
  get_url:
    url: https://raw.githubusercontent.com/Laniakea-elixir-it/Scripts/python3/galaxy_tools/py3_manage_bootstrap_user.py
    dest: "{{ galaxy_central_dir }}/manage_bootstrap_user.py"

- name: Create galaxy user with API_KEY to install tools
  shell:
    cmd: |
      docker exec -i {{ galaxy_docker_name }} \
      {{ galaxy_venv }}/bin/python3 {{ galaxy_central_dir }}/manage_bootstrap_user.py \
      -c {{ galaxy_central_dir }}/config/galaxy.yml create \
      -u {{ irida_user }} \
      -e {{ irida_email }} \
      -p {{ irida_password }}
  register: manage_bootstrap_user_output

- name: Set irida_api_key variable
  set_fact:
    irida_api_key: "{{ manage_bootstrap_user_output.stdout }}"
  run_once: true

- name: Share irida_api_key on nfs
  copy:
    content: '{{ irida_api_key }}'
    dest: '{{ irida_dir }}'

- name: Add IRIDA tool shed to tool_sheds_config.xml file
  template:
    dest: "{{ galaxy_central_dir }}/config/tool_sheds_conf.xml"
    src: tool_sheds_conf.xml.j2

- name: Copy tool list
  template:
    dest: "{{ galaxy_central_dir }}/tool_list.yml"
    src: tool_list.yml

- name: Install ephemeris in galaxy container
  shell:
    cmd: docker exec -i {{ galaxy_docker_name }} {{ galaxy_venv }}/bin/pip3 install ephemeris

- name: Install IRIDA tool shed with ephemeris
  shell:
    cmd: |
      docker exec -i {{ galaxy_docker_name }} {{ galaxy_venv }}/bin/shed-tools install \
      --toolsfile {{ galaxy_central_dir }}/tool_list.yml \
      --galaxy http://localhost \
      --api_key {{ irida_api_key }}
  register: command_result
  failed_when: "'Errored repositories (0)' not in command_result.stderr"
  notify:
    - Restart galaxy
 
