---

- name: Install nfs-kernel-server
  apt:
    name: nfs-kernel-server
    state: present

- name: Create irida directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ irida_dir }}"

- name: Add nfs directories to exports
  lineinfile:
    path: "/etc/exports"
    line: "{{ irida_dir }} {{ galaxy_url }}/24(rw,sync,no_root_squash)"
    state: present
    insertafter: EOF
  notify: Restart nfs-server

- name: Flush handlers, restart nfs-server
  meta: flush_handlers
