---

- name: Install nfs-common
  apt:
    name: nfs-common
    state: present

- name: Create irida nfs directory
  file:
    path: "{{ irida_dir }}"
    state: directory

- name: Mount nfs in fstab
  lineinfile:
    path: "/etc/fstab"
    line: "{{ galaxy_url }}:/irida {{ irida_dir }} nfs"
