---

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Disable default vhost
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Configure nginx
  template:
    dest: /etc/nginx/sites-available/irida
    src: nginx.conf.j2

- name: Enable vhosts
  file:
    src: /etc/nginx/sites-available/irida
    dest: /etc/nginx/sites-enabled/irida
    state: link

- name: Restart nginx
  service:
    name: nginx
    state: restarted
