---

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Disable default vhost
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Configure nginx
  template:
    dest: /etc/nginx/sites-available/irida
    src: nginx.conf.j2
  notify: Restart nginx

- name: Enable vhosts
  file:
    src: /etc/nginx/sites-available/irida
    dest: /etc/nginx/sites-enabled/irida
    state: link
  notify: Restart nginx
