---

- name: Create volume mountpoint directory
  file:
    path: "{{ volume_mountpoint }}"
    state: directory

- name: Create fstype on device
  filesystem:
    dev: "{{ device }}"
    fstype: "{{ fstype }}"

- name: Mount device
  mount:
    src: "{{ device }}"
    path: "{{ volume_mountpoint }}"
    state: mounted
    fstype: "{{ fstype }}"
