---
# handlers file for IRIDA-galaxy

- name: Restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes

- name: Restart tomcat8
  service:
    name: tomcat8
    state: restarted
    enabled: yes

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Restart nfs-server
  service:
    name: nfs-server
    state: restarted
    enabled: yes

- name: Restart nfs-client
  service:
    name: nfs
    state: restarted
    enabled: yes

- name: Restart galaxy
  docker_container:
    name: "{{ galaxy_docker_name }}"
    restart: yes